### ISSUE TITLE
Not detecting latest Classic Version

### ISSUE THREAD

**Issue by Trentm95** [gngrninja/PSElvUI#3]
The format of the version number has changed on the ElvUI website for the latest version of Classic ElvUI

![image](https://user-images.githubusercontent.com/30356385/91241204-d7d4f080-e709-11ea-827a-aeece4cad222.png)

 and the current regex does not match it.
https://github.com/gngrninja/PSElvUI/blob/8b0e7b6f8425765c5c826c933f8c1821299ec953/functions/private/Get-RemoteElvUiVersion.ps1#L16
![image](https://user-images.githubusercontent.com/30356385/91241002-351c7200-e709-11ea-8603-59ebebd7cedc.png)

This causes PSElvUI to think 1.24 is the latest version. Other than fixing the regex another option might be to pull the latest version from the git tags on the ELvUI Classic repo https://git.tukui.org/api/v4/projects/913/repository/tags though I'm not sure if the version is released as soon as it is tagged. Thanks for creating this module it is great!

**Comment by gngrninja** [comment]
Thank you for the detailed bug report! 

This should be fixed in the latest commit, as well as published to the PowerShell Gallery. 

If you have it installed from the gallery, use:
`Update-Module PSElvUI`

And then close/re-open your session and test it out. 

Let me know how it works, and if it is good, I will close out this issue.

**Comment by Trentm95** [comment]
It is correctly detecting the latest version now. Thanks!
